# 此配置文件会覆盖上面所依赖的其他项目的配置文件, 所以配置以此文件为准

# 公共配置
server:
  # 指定端口号
  port: 8080
  # 指定context path
  servlet:
    context-path:
mybatis:
  # MyBatis配置
  config-location: classpath:config/mybatis-config.xml

# 选择配置
spring:
  profiles:
    # 激活哪一个环境的配置文件
#    active: dev
    active: pro

---
# 开发环境
spring:
  profiles: dev
  schedule:
    corn:
      # 每天23:55检查单词是否背完
#      word-check: 0 55 23 * * ?
      word-check: 0/1 * * * * ?
  # 是否全局跨域
  all-cors: false
  shiro:
    # 允许登录尝试次数
    allow-count: 5
    remember-me:
      # rememberMeCookie加密的密钥, 建议每个项目都不一样, 默认AES算法, 密钥长度(128 256 512)位
      cipher-key: 4AvVhmFLUs0KTA3Kprsdag==
    # shiro拦截器会按顺序拦截, /**要设置在最后
    filter-chain:
      - /** = anon
  #    - /login/a = authc
  #    - /logout = logout
  #    - /getCaptcha = anon
  #    - /static/** = anon
  #    - /do = anon
  #    - /** = user
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      # 在CMD中运行: java -cp druid-1.1.10.jar com.alibaba.druid.filter.config.ConfigTools you_password 即可生成加密后的密码和公钥
      password: aM1s6D7riLEQQ/VwUPsNiL8o9XFnI5Kgrd+ujCFRJM9wcMlcuKA8f3WO7FmForOVsPRVaVGFIGtS4OKcuRHONA==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALlKU/HQiLt2P1comnrr//6tmLvwgWoxyWd2iBHbyFkx+JtHRK1NtiRaFItN6uOdlrryeDfEoU5VDDOsfzNsNmECAwEAAQ==
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.public-key}
      initial-size: 5
      max-active: 30
      filter:
        # 配置SQL监控,监控页面地址：http://127.0.0.1:8080/druid
        stat:
          enabled: true
          db-type: mysql
          # 配置slowSql的标准, 执行时间超过slowSqlMillis的就是慢. slowSqlMillis的缺省值为3000, 也就是3秒.
          slow-sql-millis: 2000
          # 允许对SlowSql进行日志记录
          log-slow-sql: true
          # 允许sql合并: 例如有2个sql语句:SELECT * FROM t WHERE id = 1, SELECT * FROM t WHERE id = 2. 会被合并成select * from t where id = ?,然后作为一条语句来统计.
          merge-sql: true
        # 配置SQL防火墙
        wall:
          enabled: true
          db-type: mysql
          config:
            # 是否允许删除记录, 一般的数据不建议物理删除, 但是某些一次性数据可以物理删除, 如验证码, session表
            delete-allow: false
            # 是否允许删除表
            drop-table-allow: false
            # 允许一次执行多条语句
            multi-statement-allow: true
            # 是否允许条件值一直为TRUE的SQL
            condition-and-alway-true-allow: true
        # 对数据库密码进行加密
        config:
          enabled: true

---
# 生产环境
spring:
  profiles: pro
  schedule:
    corn:
      word-check: 0 55 23 * * ?
  all-cors: false
  shiro:
    allow-count: 5
    remember-me:
      cipher-key: 4AvVhmFLUs0KTA3Kprsdag==
    filter-chain:
      - /** = anon
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/word0?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: QPdHyHfxg1nr5W6dSDFpBqJmFAq7BI1tiOjBZIfk9Fb5CPeexrxxR2k/hxX2kKqFQUOw2376ixHyK8GG6abAhQ==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJB9oUHZV0zu6tu+Cv2DENtEjf9H15h4/nB2IhnaeWlHP8w5ShhVFg0417XuBy2lKWkytit3klS9HsCdOwGy6M0CAwEAAQ==
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.public-key}
      initial-size: 5
      max-active: 30
      filter:
        stat:
          enabled: true
          db-type: mysql
          slow-sql-millis: 2000
          log-slow-sql: true
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
            multi-statement-allow: true
            condition-and-alway-true-allow: true
        config:
          enabled: true